---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
      tags: clickhouse
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags: clickhouse
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      tags: clickhouse
- name: Install Vector
  hosts: vector
  tasks:
    - name: Upload tar.gz Vector from remote URL
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        mode: "0755"
        timeout: 60
        force: true
        validate_certs: false
      register: get_vector
      until: get_vector is succeeded
      tags: vector
    - name: Create directrory for Vector
      ansible.builtin.file:
        state: directory
        path: "{{ vector_home }}"
        mode: "0755"
      become: true
      tags: vector
    - name: Extract Vector in the installation directory
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ vector_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ vector_home }}/bin/vector"
      become: true
      tags: vector
    - name: Set environment Vector
      ansible.builtin.template:
        src: templates/vec.sh.j2
        dest: /etc/profile.d/vec.sh
        mode: "0755"
      become: true
      tags: vector
- name: Install and configure LightHouse
  hosts: lighthouse
  handlers:
    - name: Start nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Clone LightHouse GIT repository
      ansible.builtin.git:
        repo: https://github.com/VKCOM/lighthouse
        dest: /LightHouse
        single_branch: true
        version: master
      become: true
      tags: lighthouse
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: true
        state: present
      become: true
      tags: lighthouse
    - name: Copy Nginx config
      ansible.builtin.copy:
        src: "{{ clickhouse_config }}"
        dest: "/etc/nginx/sites-enabled/default.conf"
        mode: "0755"
      become: true
      notify: Start nginx service
      tags: lighthouse
