---
- name: Install Clickhouse
  hosts: clickhouse
  tags: clickhouse
  roles:
    - name: clickhouse

- name: Install Vector
  hosts: vector
  tags: vector
  roles:
    - name: vector

- name: Install and configure LightHouse
  hosts: lighthouse
  tags: lighthouse
  roles:
    - name: lighthouse
    - name: nginx
